version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "UTC"
    commit-message:
      prefix: "ci"
      include: "scope"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "ci"
    reviewers:
      - "MikoMikocchi"
    assignees:
      - "MikoMikocchi"
