name: CI

on:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Homebrew/actions/setup-homebrew@master
      - name: Tap this repository
        run: brew tap "${{ github.repository }}"
      - name: Style
        run: brew style --fix
      - name: Audit
        run: brew audit --strict --online --tap="${{ github.repository }}"
      - name: Install
        run: |
          set -euxo pipefail
          brew install --build-from-source ./Formula/pretty-git.rb || {
            brew untap "${{ github.repository }}" || true
            brew tap "${{ github.repository }}"
            brew install --build-from-source pretty-git
          }
          brew info pretty-git
      - name: Test
        run: brew test pretty-git
