name: Dependabot Auto-Merge

on:
  pull_request_target:
    types: [opened, edited, labeled, synchronize]

permissions:
  pull-requests: write
  contents: write

jobs:
  automerge:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Approve PR
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const pull_number = context.payload.pull_request.number;
            const labels = context.payload.pull_request.labels.map(l => l.name);
            if (!labels.includes('dependencies')) {
              core.info('No dependencies label; skipping.');
              return;
            }
            await github.pulls.createReview({ owner, repo, pull_number, event: 'APPROVE' });
            core.info('Approved Dependabot PR.');

      - name: Enable auto-merge (squash)
        uses: actions/github-script@v7
        with:
          script: |
            const node_id = context.payload.pull_request.node_id;
            const query = `
              mutation ($pullRequestId: ID!, $mergeMethod: PullRequestMergeMethod!) {
                enablePullRequestAutoMerge(input: {
                  pullRequestId: $pullRequestId,
                  mergeMethod: $mergeMethod
                }) { clientMutationId }
              }
            `;
            try {
              await github.graphql(query, {
                pullRequestId: node_id,
                mergeMethod: 'SQUASH'
              });
              core.info('Auto-merge enabled.');
            } catch (e) {
              core.info(`Could not enable auto-merge (maybe disabled in repo settings): ${e.message}`);
            }
